package com.wayos_iptv.lzw.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import zxch.com.androdivoidetest.sql.LiveLink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIVE_LINK".
*/
public class LiveLinkDao extends AbstractDao<LiveLink, Void> {

    public static final String TABLENAME = "LIVE_LINK";

    /**
     * Properties of entity LiveLink.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LiveLink = new Property(0, String.class, "liveLink", false, "LIVE_LINK");
        public final static Property LiveId = new Property(1, String.class, "liveId", false, "LIVE_ID");
    }


    public LiveLinkDao(DaoConfig config) {
        super(config);
    }
    
    public LiveLinkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIVE_LINK\" (" + //
                "\"LIVE_LINK\" TEXT," + // 0: liveLink
                "\"LIVE_ID\" TEXT);"); // 1: liveId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIVE_LINK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LiveLink entity) {
        stmt.clearBindings();
 
        String liveLink = entity.getLiveLink();
        if (liveLink != null) {
            stmt.bindString(1, liveLink);
        }
 
        String liveId = entity.getLiveId();
        if (liveId != null) {
            stmt.bindString(2, liveId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LiveLink entity) {
        stmt.clearBindings();
 
        String liveLink = entity.getLiveLink();
        if (liveLink != null) {
            stmt.bindString(1, liveLink);
        }
 
        String liveId = entity.getLiveId();
        if (liveId != null) {
            stmt.bindString(2, liveId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public LiveLink readEntity(Cursor cursor, int offset) {
        LiveLink entity = new LiveLink( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // liveLink
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // liveId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LiveLink entity, int offset) {
        entity.setLiveLink(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLiveId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(LiveLink entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(LiveLink entity) {
        return null;
    }

    @Override
    public boolean hasKey(LiveLink entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
